import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TopMenu } from '@/components/TopMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-auto mb-6 lg:w-[75%] xl:w-[80%] 2xl:w-[85%]">
          {/* <div className="m-auto mb-6"> */}
          <TopMenu />

          <div className="px-6 pt-6 bg-white p-2 m-2 pb-5 rounded">{children}</div>
        </div>
        {/* {children} */}
      </body>
    </html>
  );
}
